DROP DATABASE IF EXISTS notes;
CREATE DATABASE notes;
USE notes;

CREATE TABLE user (
id INT(11) NOT NULL AUTO_INCREMENT,
login VARCHAR(20) NOT NULL,
password VARCHAR(20) NOT NULL,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
patronymic VARCHAR (50) DEFAULT NULL,
datetimeRegistration DATETIME NOT NULL,
role ENUM('REGULAR', 'SUPER') DEFAULT 'REGULAR' NOT NULL,
status ENUM('DELETED', 'ACTIVE') DEFAULT 'ACTIVE' NOT NULL,
rating DOUBLE(3,1) DEFAULT 0.0,
KEY role (role),
KEY status (status),
KEY rating (rating),
PRIMARY KEY (id),
UNIQUE KEY (login)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE session (
id INT(11) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (idUser),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE following (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
idFollowing INT(11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
FOREIGN KEY (idFollowing) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE follower (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
idFollower INT(11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES following (idFollowing) ON DELETE CASCADE,
FOREIGN KEY (idFollower) REFERENCES following (idUser) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `ignore` (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
idIgnoredUser INT(11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
FOREIGN KEY (idIgnoredUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE section (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
name VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
KEY idUser (idUser),
UNIQUE KEY (name)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE note (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
idSection INT(20) NOT NULL,
subject VARCHAR(50) NOT NULL,
datetimeCreated DATETIME NOT NULL,
rating DOUBLE(3,1) DEFAULT 0.0,
PRIMARY KEY (id),
KEY rating (rating), 
KEY idUser (idUser),
FOREIGN KEY (idSection) REFERENCES section (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE note_revision (
id INT(20) NOT NULL AUTO_INCREMENT,
idNote INT(20) NOT NULL,
body TEXT NOT NULL,
revision INT(11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idNote) REFERENCES note (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE note_rating (
id INT(20) NOT NULL AUTO_INCREMENT,
idNote INT(20) NOT NULL,
idUser INT(20) NOT NULL,
rating INT(20) NOT NULL,
PRIMARY KEY (id),
KEY rating (rating),
KEY idUser (idUser),
FOREIGN KEY (idNote) REFERENCES note (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE comment (
id INT(100) NOT NULL AUTO_INCREMENT,
idUser INT(11) NOT NULL,
idNoteRevision INT(100) NOT NULL,
comment TEXT NOT NULL,
datetimeCreated DATETIME NOT NULL,
PRIMARY KEY (id),
KEY idUser (idUser),
FOREIGN KEY (idNoteRevision) REFERENCES note_revision (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO user(login, password, firstName, lastName, patronymic, datetimeRegistration, role) VALUES ("Admin", "admin123", "Роман", "Романов", "Романович", "2020-11-21 22:10:23", 'SUPER');
SELECT * FROM user;